-- =============================================================================
-- KASUMIO data-local.sql - Exhaustive Modern Technology Knowledge Base (400+ Techs)
-- =============================================================================

-- 1. Evidence Templates (Platform Standards)
INSERT INTO evidence_templates (title, description, evidence_type, suggested_fields) VALUES
('GitHub / Git Repository', 'Demonstrate practical coding and version control through a public repository with clean commits and documentation.', 'PROJECT', '{"url_label": "Repository URL", "suggested_title": "Project Repository", "guidance": "Include a link to your public repository containing README with setup instructions and architecture notes."}'),
('Live Deployed Application', 'Demonstrate an accessible, working software product running in a production or cloud environment.', 'PROJECT', '{"url_label": "Live Demo URL", "suggested_title": "Deployed Application Demo", "guidance": "Provide the active HTTPS URL where reviewers can test the application live."}'),
('Technical Certification', 'Demonstrate standardized domain mastery validated by an accredited certification provider.', 'CERTIFICATE', '{"url_label": "Credential Verification URL", "suggested_title": "Certified Credential", "guidance": "Provide the direct verification link or credential identifier from the issuing body."}'),
('Technical Publication / Whitepaper', 'Demonstrate in-depth technical analysis, research findings, or architecture review.', 'PUBLICATION', '{"url_label": "Publication or DOI URL", "suggested_title": "Technical Publication", "guidance": "Provide a link to the published article, conference paper, or peer-reviewed document."}'),
('Competition / Hackathon Outcome', 'Demonstrate rapid problem-solving, teamwork, and execution under competition constraints.', 'OTHER', '{"url_label": "Official Results / Project URL", "suggested_title": "Hackathon Submission & Result", "guidance": "Link to the submission showcase, leaderboards, or official certificate of recognition."}');

-- 2. Exhaustive Technology Taxonomy
INSERT INTO skills (name, category, subcategory, ecosystem, canonical_name, technology_status) VALUES
('Java', 'Programming Language', 'Language', 'JVM', 'Java', 'ACTIVE'),
('Python', 'Programming Language', 'Language', 'Python', 'Python', 'ACTIVE'),
('JavaScript', 'Programming Language', 'Language', 'JavaScript', 'JavaScript', 'ACTIVE'),
('TypeScript', 'Programming Language', 'Language', 'JavaScript', 'TypeScript', 'ACTIVE'),
('C', 'Programming Language', 'Language', 'Systems', 'C', 'ACTIVE'),
('C++', 'Programming Language', 'Language', 'Systems', 'C++', 'ACTIVE'),
('C#', 'Programming Language', 'Language', '.NET', 'C#', 'ACTIVE'),
('Go', 'Programming Language', 'Language', 'Go', 'Go', 'ACTIVE'),
('Rust', 'Programming Language', 'Language', 'Systems', 'Rust', 'ACTIVE'),
('Kotlin', 'Programming Language', 'Language', 'JVM', 'Kotlin', 'ACTIVE'),
('Swift', 'Programming Language', 'Language', 'Apple', 'Swift', 'ACTIVE'),
('Dart', 'Programming Language', 'Language', 'Dart', 'Dart', 'ACTIVE'),
('Scala', 'Programming Language', 'Language', 'JVM', 'Scala', 'ACTIVE'),
('PHP', 'Programming Language', 'Language', 'PHP', 'PHP', 'ACTIVE'),
('Ruby', 'Programming Language', 'Language', 'Ruby', 'Ruby', 'ACTIVE'),
('R', 'Programming Language', 'Language', 'Data Science', 'R', 'ACTIVE'),
('Julia', 'Programming Language', 'Language', 'Scientific', 'Julia', 'ACTIVE'),
('Haskell', 'Programming Language', 'Language', 'Functional', 'Haskell', 'ACTIVE'),
('Elixir', 'Programming Language', 'Language', 'BEAM', 'Elixir', 'ACTIVE'),
('Erlang', 'Programming Language', 'Language', 'BEAM', 'Erlang', 'ACTIVE'),
('Clojure', 'Programming Language', 'Language', 'JVM', 'Clojure', 'ACTIVE'),
('F#', 'Programming Language', 'Language', '.NET', 'F#', 'ACTIVE'),
('Lua', 'Programming Language', 'Language', 'Scripting', 'Lua', 'ACTIVE'),
('Perl', 'Programming Language', 'Language', 'Scripting', 'Perl', 'ACTIVE'),
('Bash', 'Programming Language', 'Language', 'Shell', 'Bash', 'ACTIVE'),
('PowerShell', 'Programming Language', 'Language', 'Shell', 'PowerShell', 'ACTIVE'),
('Groovy', 'Programming Language', 'Language', 'JVM', 'Groovy', 'ACTIVE'),
('Objective-C', 'Programming Language', 'Language', 'Apple', 'Objective-C', 'ACTIVE'),
('Solidity', 'Programming Language', 'Language', 'Blockchain', 'Solidity', 'ACTIVE'),
('Vyper', 'Programming Language', 'Language', 'Blockchain', 'Vyper', 'ACTIVE'),
('Move', 'Programming Language', 'Language', 'Blockchain', 'Move', 'ACTIVE'),
('Cairo', 'Programming Language', 'Language', 'Blockchain', 'Cairo', 'ACTIVE'),
('Zig', 'Programming Language', 'Language', 'Systems', 'Zig', 'ACTIVE'),
('Nim', 'Programming Language', 'Language', 'Systems', 'Nim', 'ACTIVE'),
('Fortran', 'Programming Language', 'Language', 'Scientific', 'Fortran', 'ACTIVE'),
('COBOL', 'Programming Language', 'Language', 'Legacy Systems', 'COBOL', 'ACTIVE'),
('SQL', 'Programming Language', 'Language', 'SQL', 'SQL', 'ACTIVE'),
('GraphQL', 'Programming Language', 'API Query Language', 'Web', 'GraphQL', 'ACTIVE'),
('HTML5', 'Programming Language', 'Markup', 'Web', 'HTML5', 'ACTIVE'),
('CSS3', 'Programming Language', 'Styling', 'Web', 'CSS3', 'ACTIVE'),
('Assembly', 'Programming Language', 'Language', 'Hardware', 'Assembly', 'ACTIVE'),
('Spring Boot', 'Backend Development', 'Framework', 'JVM', 'Spring Boot', 'ACTIVE'),
('Spring Framework', 'Backend Development', 'Framework', 'JVM', 'Spring', 'ACTIVE'),
('Spring Cloud', 'Backend Development', 'Microservices', 'JVM', 'Spring Cloud', 'ACTIVE'),
('Spring Security', 'Backend Development', 'Security', 'JVM', 'Spring Security', 'ACTIVE'),
('Hibernate', 'Backend Development', 'ORM', 'JVM', 'Hibernate', 'ACTIVE'),
('Quarkus', 'Backend Development', 'Framework', 'JVM', 'Quarkus', 'ACTIVE'),
('Micronaut', 'Backend Development', 'Framework', 'JVM', 'Micronaut', 'ACTIVE'),
('Dropwizard', 'Backend Development', 'Framework', 'JVM', 'Dropwizard', 'ACTIVE'),
('Vert.x', 'Backend Development', 'Reactive Framework', 'JVM', 'Vert.x', 'ACTIVE'),
('Node.js', 'Backend Development', 'Runtime', 'JavaScript', 'Node.js', 'ACTIVE'),
('Express', 'Backend Development', 'Backend Framework', 'JavaScript', 'Express', 'ACTIVE'),
('NestJS', 'Backend Development', 'Backend Framework', 'JavaScript', 'NestJS', 'ACTIVE'),
('Fastify', 'Backend Development', 'Backend Framework', 'JavaScript', 'Fastify', 'ACTIVE'),
('Koa', 'Backend Development', 'Backend Framework', 'JavaScript', 'Koa', 'ACTIVE'),
('Hono', 'Backend Development', 'Edge Framework', 'JavaScript', 'Hono', 'ACTIVE'),
('Django', 'Backend Development', 'Backend Framework', 'Python', 'Django', 'ACTIVE'),
('Flask', 'Backend Development', 'Backend Framework', 'Python', 'Flask', 'ACTIVE'),
('FastAPI', 'Backend Development', 'Backend Framework', 'Python', 'FastAPI', 'ACTIVE'),
('Tornado', 'Backend Development', 'Async Framework', 'Python', 'Tornado', 'ACTIVE'),
('Celery', 'Backend Development', 'Task Queue', 'Python', 'Celery', 'ACTIVE'),
('.NET', 'Backend Development', 'Framework', '.NET', '.NET', 'ACTIVE'),
('ASP.NET Core', 'Backend Development', 'Backend Framework', '.NET', 'ASP.NET Core', 'ACTIVE'),
('Entity Framework Core', 'Backend Development', 'ORM', '.NET', 'EF Core', 'ACTIVE'),
('Ruby on Rails', 'Backend Development', 'Backend Framework', 'Ruby', 'Rails', 'ACTIVE'),
('Sinatra', 'Backend Development', 'Backend Framework', 'Ruby', 'Sinatra', 'ACTIVE'),
('Laravel', 'Backend Development', 'Backend Framework', 'PHP', 'Laravel', 'ACTIVE'),
('Symfony', 'Backend Development', 'Backend Framework', 'PHP', 'Symfony', 'ACTIVE'),
('Gin', 'Backend Development', 'Backend Framework', 'Go', 'Gin', 'ACTIVE'),
('Echo', 'Backend Development', 'Backend Framework', 'Go', 'Echo', 'ACTIVE'),
('Fiber', 'Backend Development', 'Backend Framework', 'Go', 'Fiber', 'ACTIVE'),
('Chi', 'Backend Development', 'HTTP Router', 'Go', 'Chi', 'ACTIVE'),
('Actix Web', 'Backend Development', 'Backend Framework', 'Rust', 'Actix Web', 'ACTIVE'),
('Axum', 'Backend Development', 'Backend Framework', 'Rust', 'Axum', 'ACTIVE'),
('Rocket', 'Backend Development', 'Backend Framework', 'Rust', 'Rocket', 'ACTIVE'),
('Phoenix', 'Backend Development', 'Backend Framework', 'BEAM', 'Phoenix', 'ACTIVE'),
('Ktor', 'Backend Development', 'Backend Framework', 'JVM', 'Ktor', 'ACTIVE'),
('React', 'Frontend Development', 'Library', 'JavaScript', 'React', 'ACTIVE'),
('Next.js', 'Frontend Development', 'Frontend Framework', 'JavaScript', 'Next.js', 'ACTIVE'),
('Remix', 'Frontend Development', 'Frontend Framework', 'JavaScript', 'Remix', 'ACTIVE'),
('Gatsby', 'Frontend Development', 'Static Site Generator', 'JavaScript', 'Gatsby', 'ACTIVE'),
('Vue.js', 'Frontend Development', 'Frontend Framework', 'JavaScript', 'Vue.js', 'ACTIVE'),
('Nuxt.js', 'Frontend Development', 'Frontend Framework', 'JavaScript', 'Nuxt.js', 'ACTIVE'),
('Vite', 'Frontend Development', 'Build Tool', 'JavaScript', 'Vite', 'ACTIVE'),
('Angular', 'Frontend Development', 'Frontend Framework', 'JavaScript', 'Angular', 'ACTIVE'),
('Svelte', 'Frontend Development', 'Frontend Framework', 'JavaScript', 'Svelte', 'ACTIVE'),
('SvelteKit', 'Frontend Development', 'Frontend Framework', 'JavaScript', 'SvelteKit', 'ACTIVE'),
('SolidJS', 'Frontend Development', 'Frontend Framework', 'JavaScript', 'SolidJS', 'ACTIVE'),
('Qwik', 'Frontend Development', 'Frontend Framework', 'JavaScript', 'Qwik', 'ACTIVE'),
('Astro', 'Frontend Development', 'Web Framework', 'JavaScript', 'Astro', 'ACTIVE'),
('HTMX', 'Frontend Development', 'Hypermedia Library', 'Web', 'HTMX', 'ACTIVE'),
('Alpine.js', 'Frontend Development', 'Lightweight Framework', 'JavaScript', 'Alpine.js', 'ACTIVE'),
('Web Components', 'Frontend Development', 'Web Standard', 'Web', 'Web Components', 'ACTIVE'),
('jQuery', 'Frontend Development', 'DOM Library', 'JavaScript', 'jQuery', 'ACTIVE'),
('Redux', 'Frontend Development', 'State Management', 'JavaScript', 'Redux', 'ACTIVE'),
('Redux Toolkit', 'Frontend Development', 'State Management', 'JavaScript', 'RTK', 'ACTIVE'),
('Zustand', 'Frontend Development', 'State Management', 'JavaScript', 'Zustand', 'ACTIVE'),
('MobX', 'Frontend Development', 'State Management', 'JavaScript', 'MobX', 'ACTIVE'),
('Recoil', 'Frontend Development', 'State Management', 'JavaScript', 'Recoil', 'ACTIVE'),
('Jotai', 'Frontend Development', 'State Management', 'JavaScript', 'Jotai', 'ACTIVE'),
('TanStack Query', 'Frontend Development', 'Data Fetching', 'JavaScript', 'TanStack Query', 'ACTIVE'),
('SWR', 'Frontend Development', 'Data Fetching', 'JavaScript', 'SWR', 'ACTIVE'),
('Tailwind CSS', 'Frontend Development', 'CSS Framework', 'JavaScript', 'Tailwind CSS', 'ACTIVE'),
('Bootstrap', 'Frontend Development', 'CSS Framework', 'Web', 'Bootstrap', 'ACTIVE'),
('Material UI', 'Frontend Development', 'Component Library', 'JavaScript', 'Material UI', 'ACTIVE'),
('Chakra UI', 'Frontend Development', 'Component Library', 'JavaScript', 'Chakra UI', 'ACTIVE'),
('Ant Design', 'Frontend Development', 'Component Library', 'JavaScript', 'Ant Design', 'ACTIVE'),
('Shadcn UI', 'Frontend Development', 'Component Library', 'JavaScript', 'Shadcn UI', 'ACTIVE'),
('Radix UI', 'Frontend Development', 'Component Library', 'JavaScript', 'Radix UI', 'ACTIVE'),
('Storybook', 'Frontend Development', 'UI Documentation', 'JavaScript', 'Storybook', 'ACTIVE'),
('Framer Motion', 'Frontend Development', 'Animation Library', 'JavaScript', 'Framer Motion', 'ACTIVE'),
('Three.js', 'Frontend Development', '3D Graphics', 'JavaScript', 'Three.js', 'ACTIVE'),
('WebGL', 'Frontend Development', 'Graphics API', 'Web', 'WebGL', 'ACTIVE'),
('WebGPU', 'Frontend Development', 'Graphics API', 'Web', 'WebGPU', 'ACTIVE'),
('React Native', 'Mobile Development', 'Mobile Framework', 'JavaScript', 'React Native', 'ACTIVE'),
('Flutter', 'Mobile Development', 'Mobile Framework', 'Dart', 'Flutter', 'ACTIVE'),
('SwiftUI', 'Mobile Development', 'Mobile Framework', 'Apple', 'SwiftUI', 'ACTIVE'),
('Jetpack Compose', 'Mobile Development', 'Mobile Framework', 'JVM', 'Jetpack Compose', 'ACTIVE'),
('Kotlin Multiplatform', 'Mobile Development', 'Cross-Platform', 'JVM', 'KMP', 'ACTIVE'),
('Expo', 'Mobile Development', 'Mobile Toolchain', 'JavaScript', 'Expo', 'ACTIVE'),
('Ionic', 'Mobile Development', 'Hybrid Framework', 'JavaScript', 'Ionic', 'ACTIVE'),
('Capacitor', 'Mobile Development', 'Cross-Platform Runtime', 'JavaScript', 'Capacitor', 'ACTIVE'),
('Electron', 'Desktop Development', 'Desktop Framework', 'JavaScript', 'Electron', 'ACTIVE'),
('Tauri', 'Desktop Development', 'Desktop Framework', 'Rust', 'Tauri', 'ACTIVE'),
('Qt', 'Desktop Development', 'GUI Toolkit', 'C++', 'Qt', 'ACTIVE'),
('.NET MAUI', 'Mobile Development', 'Cross-Platform Framework', '.NET', '.NET MAUI', 'ACTIVE'),
('PostgreSQL', 'Database Management', 'Relational Database', 'SQL', 'PostgreSQL', 'ACTIVE'),
('MySQL', 'Database Management', 'Relational Database', 'SQL', 'MySQL', 'ACTIVE'),
('MariaDB', 'Database Management', 'Relational Database', 'SQL', 'MariaDB', 'ACTIVE'),
('Oracle Database', 'Database Management', 'Relational Database', 'SQL', 'Oracle Database', 'ACTIVE'),
('Microsoft SQL Server', 'Database Management', 'Relational Database', 'SQL', 'SQL Server', 'ACTIVE'),
('SQLite', 'Database Management', 'Embedded Database', 'SQL', 'SQLite', 'ACTIVE'),
('CockroachDB', 'Database Management', 'Distributed SQL', 'SQL', 'CockroachDB', 'ACTIVE'),
('TiDB', 'Database Management', 'Distributed SQL', 'SQL', 'TiDB', 'ACTIVE'),
('Google Cloud Spanner', 'Database Management', 'Distributed SQL', 'GCP', 'Spanner', 'ACTIVE'),
('Amazon Aurora', 'Database Management', 'Cloud Relational Database', 'AWS', 'Aurora', 'ACTIVE'),
('YugabyteDB', 'Database Management', 'Distributed SQL', 'SQL', 'YugabyteDB', 'ACTIVE'),
('MongoDB', 'Database Management', 'Document Database', 'NoSQL', 'MongoDB', 'ACTIVE'),
('CouchDB', 'Database Management', 'Document Database', 'NoSQL', 'CouchDB', 'ACTIVE'),
('Couchbase', 'Database Management', 'Document Database', 'NoSQL', 'Couchbase', 'ACTIVE'),
('Firestore', 'Database Management', 'Cloud Document Database', 'GCP', 'Firestore', 'ACTIVE'),
('Amazon DynamoDB', 'Database Management', 'Managed NoSQL', 'AWS', 'DynamoDB', 'ACTIVE'),
('Azure Cosmos DB', 'Database Management', 'Multi-Model Database', 'Azure', 'Cosmos DB', 'ACTIVE'),
('Redis', 'Database Management', 'In-Memory Key-Value Store', 'NoSQL', 'Redis', 'ACTIVE'),
('Memcached', 'Database Management', 'In-Memory Cache', 'NoSQL', 'Memcached', 'ACTIVE'),
('Valkey', 'Database Management', 'In-Memory Store', 'NoSQL', 'Valkey', 'ACTIVE'),
('Dragonfly', 'Database Management', 'In-Memory Store', 'NoSQL', 'Dragonfly', 'ACTIVE'),
('Pinecone', 'Database Management', 'Managed Vector Database', 'AI', 'Pinecone', 'ACTIVE'),
('Weaviate', 'Database Management', 'Vector Database', 'AI', 'Weaviate', 'ACTIVE'),
('Milvus', 'Database Management', 'Vector Database', 'AI', 'Milvus', 'ACTIVE'),
('ChromaDB', 'Database Management', 'Embedded Vector Database', 'AI', 'ChromaDB', 'ACTIVE'),
('Qdrant', 'Database Management', 'Vector Database', 'AI', 'Qdrant', 'ACTIVE'),
('Pgvector', 'Database Management', 'PostgreSQL Vector Extension', 'SQL', 'Pgvector', 'ACTIVE'),
('Faiss', 'Database Management', 'Vector Search Library', 'AI', 'Faiss', 'ACTIVE'),
('InfluxDB', 'Database Management', 'Time-Series Database', 'NoSQL', 'InfluxDB', 'ACTIVE'),
('TimescaleDB', 'Database Management', 'Time-Series SQL Database', 'SQL', 'TimescaleDB', 'ACTIVE'),
('QuestDB', 'Database Management', 'Time-Series Database', 'SQL', 'QuestDB', 'ACTIVE'),
('Neo4j', 'Database Management', 'Graph Database', 'NoSQL', 'Neo4j', 'ACTIVE'),
('Amazon Neptune', 'Database Management', 'Graph Database', 'AWS', 'Neptune', 'ACTIVE'),
('ArangoDB', 'Database Management', 'Multi-Model Graph Database', 'NoSQL', 'ArangoDB', 'ACTIVE'),
('Snowflake', 'Database Management', 'Cloud Data Warehouse', 'Data', 'Snowflake', 'ACTIVE'),
('Google BigQuery', 'Database Management', 'Serverless Data Warehouse', 'GCP', 'BigQuery', 'ACTIVE'),
('Amazon Redshift', 'Database Management', 'Cloud Data Warehouse', 'AWS', 'Redshift', 'ACTIVE'),
('ClickHouse', 'Database Management', 'Columnar OLAP Database', 'Data', 'ClickHouse', 'ACTIVE'),
('Apache Druid', 'Database Management', 'Real-Time Analytics DB', 'Data', 'Druid', 'ACTIVE'),
('Apache Pinot', 'Database Management', 'Real-Time OLAP Datastore', 'Data', 'Pinot', 'ACTIVE'),
('DuckDB', 'Database Management', 'In-Process Analytical Database', 'Data', 'DuckDB', 'ACTIVE'),
('Trino', 'Database Management', 'Distributed SQL Query Engine', 'Data', 'Trino', 'ACTIVE'),
('Presto', 'Database Management', 'Distributed Query Engine', 'Data', 'Presto', 'ACTIVE'),
('Elasticsearch', 'Database Management', 'Search & Analytics Engine', 'Search', 'Elasticsearch', 'ACTIVE'),
('OpenSearch', 'Database Management', 'Search Engine', 'Search', 'OpenSearch', 'ACTIVE'),
('Meilisearch', 'Database Management', 'Fast Search Engine', 'Search', 'Meilisearch', 'ACTIVE'),
('Apache Spark', 'Data Engineering', 'Distributed Processing Engine', 'Data', 'Spark', 'ACTIVE'),
('PySpark', 'Data Engineering', 'Python Spark API', 'Python', 'PySpark', 'ACTIVE'),
('Apache Kafka', 'Data Engineering', 'Distributed Event Streaming', 'Data', 'Kafka', 'ACTIVE'),
('Apache Flink', 'Data Engineering', 'Stream Processing Engine', 'Data', 'Flink', 'ACTIVE'),
('Apache Airflow', 'Data Engineering', 'Workflow Orchestration', 'Data', 'Airflow', 'ACTIVE'),
('Apache Beam', 'Data Engineering', 'Unified Batch & Stream Pipeline', 'Data', 'Beam', 'ACTIVE'),
('dbt', 'Data Engineering', 'Data Transformation Tool', 'Data', 'dbt', 'ACTIVE'),
('Apache Cassandra', 'Data Engineering', 'Wide-Column Distributed Store', 'Data', 'Cassandra', 'ACTIVE'),
('Apache Hadoop', 'Data Engineering', 'Distributed Storage & Compute', 'Data', 'Hadoop', 'ACTIVE'),
('Apache Hive', 'Data Engineering', 'Data Warehouse Software', 'Data', 'Hive', 'ACTIVE'),
('Apache Iceberg', 'Data Engineering', 'Open Table Format', 'Data', 'Iceberg', 'ACTIVE'),
('Delta Lake', 'Data Engineering', 'Storage Layer', 'Data', 'Delta Lake', 'ACTIVE'),
('Apache Hudi', 'Data Engineering', 'Streaming Data Lakehouse Platform', 'Data', 'Hudi', 'ACTIVE'),
('Databricks', 'Data Engineering', 'Unified Data Analytics Platform', 'Data', 'Databricks', 'ACTIVE'),
('Polars', 'Data Engineering', 'Fast DataFrame Library', 'Rust', 'Polars', 'ACTIVE'),
('Pandas', 'Data Engineering', 'Data Analysis Library', 'Python', 'Pandas', 'ACTIVE'),
('NumPy', 'Data Engineering', 'Numerical Computing Library', 'Python', 'NumPy', 'ACTIVE'),
('Prefect', 'Data Engineering', 'Workflow Orchestration', 'Python', 'Prefect', 'ACTIVE'),
('Dagster', 'Data Engineering', 'Data Orchestrator', 'Python', 'Dagster', 'ACTIVE'),
('Mage', 'Data Engineering', 'Modern Data Pipeline Tool', 'Python', 'Mage', 'ACTIVE'),
('Debezium', 'Data Engineering', 'Change Data Capture (CDC)', 'Data', 'Debezium', 'ACTIVE'),
('RabbitMQ', 'Data Engineering', 'Message Broker', 'DevOps', 'RabbitMQ', 'ACTIVE'),
('Apache Pulsar', 'Data Engineering', 'Distributed Messaging & Streaming', 'Data', 'Pulsar', 'ACTIVE'),
('NATS', 'Data Engineering', 'Cloud-Native Messaging System', 'DevOps', 'NATS', 'ACTIVE'),
('AWS SQS', 'Data Engineering', 'Managed Message Queue', 'AWS', 'SQS', 'ACTIVE'),
('AWS SNS', 'Data Engineering', 'Pub/Sub Messaging', 'AWS', 'SNS', 'ACTIVE'),
('ETL', 'Data Engineering', 'Data Integration Practice', 'Data', 'ETL', 'ACTIVE'),
('Data Warehousing', 'Data Engineering', 'Architecture Discipline', 'Data', 'Data Warehousing', 'ACTIVE'),
('Data Science', 'Data Engineering', 'Analytical Discipline', 'Data', 'Data Science', 'ACTIVE'),
('Amazon Web Services', 'Cloud Platforms', 'Cloud Provider', 'AWS', 'AWS', 'ACTIVE'),
('Microsoft Azure', 'Cloud Platforms', 'Cloud Provider', 'Azure', 'Azure', 'ACTIVE'),
('Google Cloud Platform', 'Cloud Platforms', 'Cloud Provider', 'GCP', 'Google Cloud', 'ACTIVE'),
('Oracle Cloud Infrastructure', 'Cloud Platforms', 'Cloud Provider', 'Oracle', 'OCI', 'ACTIVE'),
('IBM Cloud', 'Cloud Platforms', 'Cloud Provider', 'IBM', 'IBM Cloud', 'ACTIVE'),
('Cloudflare', 'Cloud Platforms', 'Edge & CDN Platform', 'Cloudflare', 'Cloudflare', 'ACTIVE'),
('Vercel', 'Cloud Platforms', 'Frontend Cloud Platform', 'Vercel', 'Vercel', 'ACTIVE'),
('Netlify', 'Cloud Platforms', 'Composable Web Platform', 'Netlify', 'Netlify', 'ACTIVE'),
('DigitalOcean', 'Cloud Platforms', 'Cloud Infrastructure', 'DigitalOcean', 'DigitalOcean', 'ACTIVE'),
('Heroku', 'Cloud Platforms', 'PaaS Platform', 'Heroku', 'Heroku', 'ACTIVE'),
('Supabase', 'Cloud Platforms', 'Open Source Firebase Alternative', 'Open Source', 'Supabase', 'ACTIVE'),
('Firebase', 'Cloud Platforms', 'App Development Platform', 'GCP', 'Firebase', 'ACTIVE'),
('Railway', 'Cloud Platforms', 'Deployment Platform', 'Cloud', 'Railway', 'ACTIVE'),
('Render', 'Cloud Platforms', 'Cloud Application Platform', 'Cloud', 'Render', 'ACTIVE'),
('Fly.io', 'Cloud Platforms', 'Global Application Platform', 'Cloud', 'Fly.io', 'ACTIVE'),
('Hetzner', 'Cloud Platforms', 'Cloud Hosting & Servers', 'Cloud', 'Hetzner', 'ACTIVE'),
('AWS Lambda', 'Cloud Platforms', 'Serverless Compute', 'AWS', 'AWS Lambda', 'ACTIVE'),
('Google Cloud Functions', 'Cloud Platforms', 'Serverless Compute', 'GCP', 'Cloud Functions', 'ACTIVE'),
('Azure Functions', 'Cloud Platforms', 'Serverless Compute', 'Azure', 'Azure Functions', 'ACTIVE'),
('Cloudflare Workers', 'Cloud Platforms', 'Serverless Edge Compute', 'Cloudflare', 'Workers', 'ACTIVE'),
('AWS ECS', 'Cloud Platforms', 'Container Orchestration', 'AWS', 'ECS', 'ACTIVE'),
('AWS Fargate', 'Cloud Platforms', 'Serverless Container Compute', 'AWS', 'Fargate', 'ACTIVE'),
('Amazon S3', 'Cloud Platforms', 'Object Storage', 'AWS', 'S3', 'ACTIVE'),
('Google Cloud Storage', 'Cloud Platforms', 'Object Storage', 'GCP', 'GCS', 'ACTIVE'),
('Azure Blob Storage', 'Cloud Platforms', 'Object Storage', 'Azure', 'Blob Storage', 'ACTIVE'),
('Docker', 'DevOps', 'Containerization', 'DevOps', 'Docker', 'ACTIVE'),
('Kubernetes', 'DevOps', 'Container Orchestration', 'DevOps', 'Kubernetes', 'ACTIVE'),
('Helm', 'DevOps', 'Kubernetes Package Manager', 'DevOps', 'Helm', 'ACTIVE'),
('Terraform', 'DevOps', 'Infrastructure as Code', 'DevOps', 'Terraform', 'ACTIVE'),
('OpenTofu', 'DevOps', 'Infrastructure as Code', 'DevOps', 'OpenTofu', 'ACTIVE'),
('Pulumi', 'DevOps', 'Infrastructure as Code', 'DevOps', 'Pulumi', 'ACTIVE'),
('Ansible', 'DevOps', 'Configuration Management', 'DevOps', 'Ansible', 'ACTIVE'),
('Puppet', 'DevOps', 'Configuration Management', 'DevOps', 'Puppet', 'ACTIVE'),
('Chef', 'DevOps', 'Configuration Management', 'DevOps', 'Chef', 'ACTIVE'),
('Vagrant', 'DevOps', 'Development Environment Automation', 'DevOps', 'Vagrant', 'ACTIVE'),
('Packer', 'DevOps', 'Machine Image Automation', 'DevOps', 'Packer', 'ACTIVE'),
('Jenkins', 'DevOps', 'Automation Server', 'DevOps', 'Jenkins', 'ACTIVE'),
('GitHub Actions', 'DevOps', 'CI/CD Automation', 'GitHub', 'GitHub Actions', 'ACTIVE'),
('GitLab CI/CD', 'DevOps', 'Continuous Integration Platform', 'GitLab', 'GitLab CI/CD', 'ACTIVE'),
('CircleCI', 'DevOps', 'Continuous Integration Platform', 'DevOps', 'CircleCI', 'ACTIVE'),
('ArgoCD', 'DevOps', 'Declarative GitOps Engine', 'DevOps', 'ArgoCD', 'ACTIVE'),
('Flux', 'DevOps', 'GitOps Operator for Kubernetes', 'DevOps', 'Flux', 'ACTIVE'),
('Tekton', 'DevOps', 'Cloud-Native CI/CD Framework', 'DevOps', 'Tekton', 'ACTIVE'),
('Spinnaker', 'DevOps', 'Multi-Cloud Continuous Delivery', 'DevOps', 'Spinnaker', 'ACTIVE'),
('Linux', 'DevOps', 'Operating System', 'Systems', 'Linux', 'ACTIVE'),
('Ubuntu', 'DevOps', 'Linux Distribution', 'Systems', 'Ubuntu', 'ACTIVE'),
('Alpine Linux', 'DevOps', 'Lightweight Linux Distribution', 'Systems', 'Alpine', 'ACTIVE'),
('Debian', 'DevOps', 'Linux Distribution', 'Systems', 'Debian', 'ACTIVE'),
('RHEL', 'DevOps', 'Enterprise Linux Distribution', 'Systems', 'RHEL', 'ACTIVE'),
('Nginx', 'DevOps', 'Web Server & Reverse Proxy', 'DevOps', 'Nginx', 'ACTIVE'),
('Apache HTTP Server', 'DevOps', 'Web Server', 'DevOps', 'Apache', 'ACTIVE'),
('Caddy', 'DevOps', 'Modern Web Server', 'DevOps', 'Caddy', 'ACTIVE'),
('Traefik', 'DevOps', 'Cloud-Native Application Proxy', 'DevOps', 'Traefik', 'ACTIVE'),
('HAProxy', 'DevOps', 'Load Balancer', 'DevOps', 'HAProxy', 'ACTIVE'),
('Envoy', 'DevOps', 'Edge and Service Proxy', 'DevOps', 'Envoy', 'ACTIVE'),
('Istio', 'DevOps', 'Service Mesh', 'DevOps', 'Istio', 'ACTIVE'),
('Linkerd', 'DevOps', 'Lightweight Service Mesh', 'DevOps', 'Linkerd', 'ACTIVE'),
('Cilium', 'DevOps', 'eBPF-based Networking & Security', 'DevOps', 'Cilium', 'ACTIVE'),
('CI/CD', 'DevOps', 'Continuous Integration & Delivery', 'DevOps', 'CI/CD', 'ACTIVE'),
('Infrastructure as Code', 'DevOps', 'Infrastructure Automation', 'DevOps', 'IaC', 'ACTIVE'),
('Prometheus', 'DevOps', 'Metrics & Monitoring System', 'DevOps', 'Prometheus', 'ACTIVE'),
('Grafana', 'DevOps', 'Observability Visualization', 'DevOps', 'Grafana', 'ACTIVE'),
('Datadog', 'DevOps', 'Cloud Monitoring & APM', 'DevOps', 'Datadog', 'ACTIVE'),
('Splunk', 'DevOps', 'Log Analysis & SIEM', 'DevOps', 'Splunk', 'ACTIVE'),
('Dynatrace', 'DevOps', 'Software Intelligence Platform', 'DevOps', 'Dynatrace', 'ACTIVE'),
('New Relic', 'DevOps', 'Observability & APM Platform', 'DevOps', 'New Relic', 'ACTIVE'),
('OpenTelemetry', 'DevOps', 'Observability Framework', 'DevOps', 'OpenTelemetry', 'ACTIVE'),
('Jaeger', 'DevOps', 'Distributed Tracing System', 'DevOps', 'Jaeger', 'ACTIVE'),
('Zipkin', 'DevOps', 'Distributed Tracing System', 'DevOps', 'Zipkin', 'ACTIVE'),
('ELK Stack', 'DevOps', 'Log Management Platform', 'Search', 'ELK Stack', 'ACTIVE'),
('Logstash', 'DevOps', 'Log Ingestion Engine', 'Search', 'Logstash', 'ACTIVE'),
('Kibana', 'DevOps', 'Log & Data Visualization', 'Search', 'Kibana', 'ACTIVE'),
('Grafana Loki', 'DevOps', 'Log Aggregation System', 'DevOps', 'Loki', 'ACTIVE'),
('Grafana Tempo', 'DevOps', 'Distributed Tracing Backend', 'DevOps', 'Tempo', 'ACTIVE'),
('Sentry', 'DevOps', 'Application Monitoring & Error Tracking', 'DevOps', 'Sentry', 'ACTIVE'),
('PagerDuty', 'DevOps', 'Incident Response Platform', 'DevOps', 'PagerDuty', 'ACTIVE'),
('Machine Learning', 'AI/ML', 'Core Discipline', 'AI', 'Machine Learning', 'ACTIVE'),
('Deep Learning', 'AI/ML', 'Neural Networks Discipline', 'AI', 'Deep Learning', 'ACTIVE'),
('Natural Language Processing', 'AI/ML', 'Language Intelligence', 'AI', 'NLP', 'ACTIVE'),
('Computer Vision', 'AI/ML', 'Visual Intelligence', 'AI', 'Computer Vision', 'ACTIVE'),
('Reinforcement Learning', 'AI/ML', 'Decision Intelligence', 'AI', 'RL', 'ACTIVE'),
('Generative Adversarial Networks', 'AI/ML', 'Generative Modeling', 'AI', 'GAN', 'ACTIVE'),
('PyTorch', 'AI/ML', 'Deep Learning Framework', 'Python', 'PyTorch', 'ACTIVE'),
('TensorFlow', 'AI/ML', 'Machine Learning Platform', 'Python', 'TensorFlow', 'ACTIVE'),
('scikit-learn', 'AI/ML', 'Machine Learning Library', 'Python', 'scikit-learn', 'ACTIVE'),
('Keras', 'AI/ML', 'High-Level Neural Networks API', 'Python', 'Keras', 'ACTIVE'),
('JAX', 'AI/ML', 'High-Performance Numerical Computing', 'Python', 'JAX', 'ACTIVE'),
('XGBoost', 'AI/ML', 'Gradient Boosting Library', 'Python', 'XGBoost', 'ACTIVE'),
('LightGBM', 'AI/ML', 'Gradient Boosting Framework', 'Python', 'LightGBM', 'ACTIVE'),
('CatBoost', 'AI/ML', 'Gradient Boosting on Decision Trees', 'Python', 'CatBoost', 'ACTIVE'),
('OpenCV', 'AI/ML', 'Computer Vision Library', 'Python', 'OpenCV', 'ACTIVE'),
('spaCy', 'AI/ML', 'Industrial NLP Library', 'Python', 'spaCy', 'ACTIVE'),
('NLTK', 'AI/ML', 'Natural Language Toolkit', 'Python', 'NLTK', 'ACTIVE'),
('Hugging Face', 'AI/ML', 'AI Community & Model Hub', 'AI', 'Hugging Face', 'ACTIVE'),
('Transformers', 'AI/ML', 'State-of-the-art ML Library', 'AI', 'Transformers', 'ACTIVE'),
('Diffusers', 'AI/ML', 'Diffusion Models Library', 'AI', 'Diffusers', 'ACTIVE'),
('ONNX', 'AI/ML', 'Open Neural Network Exchange', 'AI', 'ONNX', 'ACTIVE'),
('TensorRT', 'AI/ML', 'Deep Learning Inference Optimizer', 'AI', 'TensorRT', 'ACTIVE'),
('Triton Inference Server', 'AI/ML', 'Production AI Serving', 'AI', 'Triton', 'ACTIVE'),
('vLLM', 'AI/ML', 'High-Throughput LLM Serving', 'AI', 'vLLM', 'ACTIVE'),
('Ollama', 'AI/ML', 'Local LLM Runner', 'AI', 'Ollama', 'ACTIVE'),
('DeepSpeed', 'AI/ML', 'Distributed Deep Learning Optimization', 'Python', 'DeepSpeed', 'ACTIVE'),
('Ray', 'AI/ML', 'Distributed Compute Framework', 'Python', 'Ray', 'ACTIVE'),
('MLflow', 'AI/ML', 'ML Lifecycle Management', 'Python', 'MLflow', 'ACTIVE'),
('Kubeflow', 'AI/ML', 'Kubernetes Machine Learning Platform', 'DevOps', 'Kubeflow', 'ACTIVE'),
('Weights & Biases', 'AI/ML', 'ML Experiment Tracking', 'AI', 'W&B', 'ACTIVE'),
('MLOps', 'AI/ML', 'Machine Learning Operations', 'AI', 'MLOps', 'ACTIVE'),
('Large Language Models', 'Generative AI', 'Foundational AI Models', 'AI', 'LLM', 'ACTIVE'),
('GPT-4', 'Generative AI', 'Commercial Frontier Model', 'AI', 'GPT-4', 'ACTIVE'),
('Claude', 'Generative AI', 'Commercial Frontier Model', 'AI', 'Claude', 'ACTIVE'),
('Llama 3', 'Generative AI', 'Open Foundation Model', 'AI', 'Llama', 'ACTIVE'),
('Mistral', 'Generative AI', 'Open Foundation Model', 'AI', 'Mistral', 'ACTIVE'),
('Gemini', 'Generative AI', 'Multimodal Foundation Model', 'AI', 'Gemini', 'ACTIVE'),
('RAG', 'Generative AI', 'Retrieval-Augmented Generation', 'AI', 'RAG', 'ACTIVE'),
('Advanced RAG', 'Generative AI', 'Complex Retrieval Pipelines', 'AI', 'Advanced RAG', 'ACTIVE'),
('Graph RAG', 'Generative AI', 'Knowledge Graph Retrieval', 'AI', 'Graph RAG', 'ACTIVE'),
('Vector Embeddings', 'Generative AI', 'Semantic Representation', 'AI', 'Embeddings', 'ACTIVE'),
('Semantic Search', 'Generative AI', 'Neural Information Retrieval', 'AI', 'Semantic Search', 'ACTIVE'),
('Prompt Engineering', 'Generative AI', 'Prompt Optimization Technique', 'AI', 'Prompt Engineering', 'ACTIVE'),
('DSPy', 'Generative AI', 'Algorithmic Prompt Programming', 'Python', 'DSPy', 'ACTIVE'),
('Fine-tuning', 'Generative AI', 'Model Customization', 'AI', 'Fine-tuning', 'ACTIVE'),
('LoRA', 'Generative AI', 'Low-Rank Adaptation', 'AI', 'LoRA', 'ACTIVE'),
('QLoRA', 'Generative AI', 'Quantized Low-Rank Adaptation', 'AI', 'QLoRA', 'ACTIVE'),
('RLHF', 'Generative AI', 'Reinforcement Learning from Human Feedback', 'AI', 'RLHF', 'ACTIVE'),
('AI Safety & Alignment', 'Generative AI', 'Safety Principles & Guardrails', 'AI', 'AI Safety', 'ACTIVE'),
('LangChain', 'Generative AI', 'LLM Application Framework', 'Python', 'LangChain', 'ACTIVE'),
('LangGraph', 'Generative AI', 'Multi-Agent Graph Workflows', 'Python', 'LangGraph', 'ACTIVE'),
('LlamaIndex', 'Generative AI', 'Data Framework for LLMs', 'Python', 'LlamaIndex', 'ACTIVE'),
('Semantic Kernel', 'Generative AI', 'Enterprise AI Framework', '.NET', 'Semantic Kernel', 'ACTIVE'),
('Haystack', 'Generative AI', 'NLP & RAG Framework', 'Python', 'Haystack', 'ACTIVE'),
('AI Agents', 'AI Agents', 'Autonomous Software Entities', 'AI', 'AI Agents', 'ACTIVE'),
('Agentic Workflows', 'AI Agents', 'Iterative Execution Pipelines', 'AI', 'Agentic Workflows', 'ACTIVE'),
('Tool Calling', 'AI Agents', 'External API & Tool Execution', 'AI', 'Tool Calling', 'ACTIVE'),
('Function Calling', 'AI Agents', 'Structured API Interfacing', 'AI', 'Function Calling', 'ACTIVE'),
('Agent Memory', 'AI Agents', 'Short & Long Term Context Storage', 'AI', 'Agent Memory', 'ACTIVE'),
('Agent Orchestration', 'AI Agents', 'Multi-Agent Coordination', 'AI', 'Agent Orchestration', 'ACTIVE'),
('Multi-Agent Systems', 'AI Agents', 'Collaborative Agent Swarms', 'AI', 'Multi-Agent Systems', 'ACTIVE'),
('CrewAI', 'AI Agents', 'Role-Playing Multi-Agent Framework', 'Python', 'CrewAI', 'ACTIVE'),
('AutoGen', 'AI Agents', 'Multi-Agent Conversation Framework', 'Python', 'AutoGen', 'ACTIVE'),
('Model Context Protocol', 'AI Agents', 'Standardized Tool & Resource Protocol', 'AI', 'MCP', 'ACTIVE'),
('Application Security', 'Cybersecurity', 'Software Security Practice', 'Security', 'AppSec', 'ACTIVE'),
('Network Security', 'Cybersecurity', 'Infrastructure Security', 'Security', 'Network Security', 'ACTIVE'),
('Cloud Security', 'Cybersecurity', 'Cloud Protection Discipline', 'Security', 'Cloud Security', 'ACTIVE'),
('Penetration Testing', 'Cybersecurity', 'Offensive Security Testing', 'Security', 'Penetration Testing', 'ACTIVE'),
('Ethical Hacking', 'Cybersecurity', 'Security Assessment', 'Security', 'Ethical Hacking', 'ACTIVE'),
('OWASP Top 10', 'Cybersecurity', 'Web Vulnerability Standard', 'Security', 'OWASP Top 10', 'ACTIVE'),
('SAST', 'Cybersecurity', 'Static Application Security Testing', 'Security', 'SAST', 'ACTIVE'),
('DAST', 'Cybersecurity', 'Dynamic Application Security Testing', 'Security', 'DAST', 'ACTIVE'),
('IAM', 'Cybersecurity', 'Identity & Access Management', 'Security', 'IAM', 'ACTIVE'),
('OAuth 2.0', 'Cybersecurity', 'Authorization Protocol', 'Security', 'OAuth 2.0', 'ACTIVE'),
('OpenID Connect', 'Cybersecurity', 'Authentication Protocol', 'Security', 'OIDC', 'ACTIVE'),
('JSON Web Tokens', 'Cybersecurity', 'Security Token Standard', 'Security', 'JWT', 'ACTIVE'),
('SAML', 'Cybersecurity', 'Enterprise Identity Federation', 'Security', 'SAML', 'ACTIVE'),
('Zero Trust Architecture', 'Cybersecurity', 'Security Paradigm', 'Security', 'Zero Trust', 'ACTIVE'),
('Cryptography', 'Cybersecurity', 'Mathematical Encryption Discipline', 'Security', 'Cryptography', 'ACTIVE'),
('SIEM', 'Cybersecurity', 'Security Information & Event Management', 'Security', 'SIEM', 'ACTIVE'),
('SOC', 'Cybersecurity', 'Security Operations Center', 'Security', 'SOC', 'ACTIVE'),
('Threat Modeling', 'Cybersecurity', 'Proactive Risk Assessment', 'Security', 'Threat Modeling', 'ACTIVE'),
('HashiCorp Vault', 'Cybersecurity', 'Secrets Management Platform', 'Security', 'Vault', 'ACTIVE'),
('SonarQube', 'Cybersecurity', 'Code Quality & Security Analysis', 'Software Engineering', 'SonarQube', 'ACTIVE'),
('Snyk', 'Cybersecurity', 'Developer Security Platform', 'Security', 'Snyk', 'ACTIVE'),
('Trivy', 'Cybersecurity', 'Container & IaC Security Scanner', 'Security', 'Trivy', 'ACTIVE'),
('Burp Suite', 'Cybersecurity', 'Web Vulnerability Scanner', 'Security', 'Burp Suite', 'ACTIVE'),
('Wireshark', 'Cybersecurity', 'Network Protocol Analyzer', 'Security', 'Wireshark', 'ACTIVE'),
('Unit Testing', 'Testing', 'Testing Methodology', 'Software Engineering', 'Unit Testing', 'ACTIVE'),
('Integration Testing', 'Testing', 'Testing Methodology', 'Software Engineering', 'Integration Testing', 'ACTIVE'),
('End-to-End Testing', 'Testing', 'Testing Methodology', 'Software Engineering', 'E2E Testing', 'ACTIVE'),
('Test-Driven Development', 'Testing', 'Engineering Practice', 'Software Engineering', 'TDD', 'ACTIVE'),
('JUnit 5', 'Testing', 'Java Testing Framework', 'JVM', 'JUnit', 'ACTIVE'),
('Mockito', 'Testing', 'Java Mocking Library', 'JVM', 'Mockito', 'ACTIVE'),
('Testcontainers', 'Testing', 'Integration Testing with Containers', 'DevOps', 'Testcontainers', 'ACTIVE'),
('PyTest', 'Testing', 'Python Testing Framework', 'Python', 'PyTest', 'ACTIVE'),
('Jest', 'Testing', 'JavaScript Testing Framework', 'JavaScript', 'Jest', 'ACTIVE'),
('Vitest', 'Testing', 'Next Generation Testing Framework', 'JavaScript', 'Vitest', 'ACTIVE'),
('Cypress', 'Testing', 'Frontend Testing Tool', 'JavaScript', 'Cypress', 'ACTIVE'),
('Playwright', 'Testing', 'Modern End-to-End Testing', 'Testing', 'Playwright', 'ACTIVE'),
('Selenium', 'Testing', 'Browser Automation Tool', 'Testing', 'Selenium', 'ACTIVE'),
('Appium', 'Testing', 'Mobile Automation Framework', 'Testing', 'Appium', 'ACTIVE'),
('Postman', 'Testing', 'API Development & Testing Tool', 'Web', 'Postman', 'ACTIVE'),
('k6', 'Testing', 'Load & Performance Testing Tool', 'Testing', 'k6', 'ACTIVE'),
('Apache JMeter', 'Testing', 'Performance & Load Testing', 'Testing', 'JMeter', 'ACTIVE'),
('Data Structures & Algorithms', 'Computer Science', 'Foundational CS Concepts', 'Computer Science', 'DSA', 'ACTIVE'),
('Object-Oriented Design', 'Software Engineering', 'Design Paradigm', 'Software Engineering', 'OOD', 'ACTIVE'),
('System Design', 'Software Engineering', 'Architecture Discipline', 'Software Engineering', 'System Design', 'ACTIVE'),
('Microservices Architecture', 'Software Engineering', 'Architecture Pattern', 'Software Engineering', 'Microservices', 'ACTIVE'),
('Monolithic Architecture', 'Software Engineering', 'Architecture Pattern', 'Software Engineering', 'Monolith', 'ACTIVE'),
('Event-Driven Architecture', 'Software Engineering', 'Architecture Pattern', 'Software Engineering', 'EDA', 'ACTIVE'),
('Domain-Driven Design', 'Software Engineering', 'Software Design Approach', 'Software Engineering', 'DDD', 'ACTIVE'),
('CQRS', 'Software Engineering', 'Command Query Responsibility Segregation', 'Software Engineering', 'CQRS', 'ACTIVE'),
('Event Sourcing', 'Software Engineering', 'State Persistence Pattern', 'Software Engineering', 'Event Sourcing', 'ACTIVE'),
('REST API Design', 'Software Engineering', 'Web Architecture', 'Web', 'REST API Design', 'ACTIVE'),
('gRPC', 'Software Engineering', 'High Performance RPC Framework', 'Web', 'gRPC', 'ACTIVE'),
('Protocol Buffers', 'Software Engineering', 'Binary Serialization Format', 'Go', 'Protobuf', 'ACTIVE'),
('WebSockets', 'Software Engineering', 'Real-Time Bidirectional Protocol', 'Web', 'WebSockets', 'ACTIVE'),
('WebRTC', 'Software Engineering', 'Real-Time Peer Communication', 'Web', 'WebRTC', 'ACTIVE'),
('Server-Sent Events', 'Software Engineering', 'Unidirectional Real-Time Streaming', 'Web', 'SSE', 'ACTIVE'),
('Distributed Caching', 'Software Engineering', 'Performance Pattern', 'Software Engineering', 'Distributed Caching', 'ACTIVE'),
('Load Balancing', 'Software Engineering', 'Scalability Technique', 'Software Engineering', 'Load Balancing', 'ACTIVE'),
('Rate Limiting', 'Software Engineering', 'Resilience Technique', 'Software Engineering', 'Rate Limiting', 'ACTIVE'),
('API Gateway', 'Software Engineering', 'Architecture Pattern', 'Software Engineering', 'API Gateway', 'ACTIVE'),
('Circuit Breaker', 'Software Engineering', 'Fault Tolerance Pattern', 'Software Engineering', 'Circuit Breaker', 'ACTIVE'),
('Service Mesh', 'Software Engineering', 'Infrastructure Layer', 'DevOps', 'Service Mesh', 'ACTIVE'),
('High Availability', 'Software Engineering', 'System Reliability Concept', 'Software Engineering', 'High Availability', 'ACTIVE'),
('Database Sharding', 'Software Engineering', 'Horizontal Partitioning', 'Database', 'Sharding', 'ACTIVE'),
('Concurrency & Multithreading', 'Computer Science', 'Parallel Execution Concepts', 'Computer Science', 'Concurrency', 'ACTIVE'),
('Asynchronous Programming', 'Software Engineering', 'Non-Blocking Execution', 'Software Engineering', 'Async', 'ACTIVE'),
('Git & Version Control', 'Software Engineering', 'Version Management', 'DevOps', 'Git', 'ACTIVE'),
('Web Security & Authentication', 'Security', 'Core Security Principle', 'Web', 'Web Security', 'ACTIVE'),
('Blockchain', 'Emerging Technology', 'Distributed Ledger Discipline', 'Blockchain', 'Blockchain', 'ACTIVE'),
('Ethereum', 'Emerging Technology', 'Smart Contract Platform', 'Blockchain', 'Ethereum', 'ACTIVE'),
('Bitcoin', 'Emerging Technology', 'Cryptocurrency Protocol', 'Blockchain', 'Bitcoin', 'ACTIVE'),
('Solana', 'Emerging Technology', 'High-Performance Blockchain', 'Blockchain', 'Solana', 'ACTIVE'),
('Smart Contracts', 'Emerging Technology', 'Decentralized Logic', 'Blockchain', 'Smart Contracts', 'ACTIVE'),
('Web3.js', 'Emerging Technology', 'Ethereum JavaScript API', 'Blockchain', 'Web3.js', 'ACTIVE'),
('Ethers.js', 'Emerging Technology', 'Ethereum Library', 'Blockchain', 'Ethers.js', 'ACTIVE'),
('Hardhat', 'Emerging Technology', 'Ethereum Development Environment', 'Blockchain', 'Hardhat', 'ACTIVE'),
('Foundry', 'Emerging Technology', 'Smart Contract Development Toolchain', 'Blockchain', 'Foundry', 'ACTIVE'),
('IPFS', 'Emerging Technology', 'Peer-to-Peer Hypermedia Protocol', 'Blockchain', 'IPFS', 'ACTIVE'),
('Zero-Knowledge Proofs', 'Emerging Technology', 'Cryptographic Privacy Protocol', 'Blockchain', 'ZK Proofs', 'ACTIVE'),
('IoT', 'Emerging Technology', 'Internet of Things', 'IoT', 'IoT', 'ACTIVE'),
('MQTT', 'Emerging Technology', 'Lightweight IoT Protocol', 'IoT', 'MQTT', 'ACTIVE'),
('Embedded C', 'Emerging Technology', 'Firmware Programming', 'Systems', 'Embedded C', 'ACTIVE'),
('ROS', 'Emerging Technology', 'Robot Operating System', 'Robotics', 'ROS', 'ACTIVE'),
('Arduino', 'Emerging Technology', 'Microcontroller Platform', 'IoT', 'Arduino', 'ACTIVE'),
('Raspberry Pi', 'Emerging Technology', 'Single-Board Computer', 'IoT', 'Raspberry Pi', 'ACTIVE'),
('Edge Computing', 'Emerging Technology', 'Distributed Edge Processing', 'Cloud', 'Edge Computing', 'ACTIVE'),
('Quantum Computing', 'Emerging Technology', 'Quantum Physics Compute', 'Quantum', 'Quantum Computing', 'ACTIVE'),
('Qiskit', 'Emerging Technology', 'Quantum SDK', 'Python', 'Qiskit', 'ACTIVE'),
('WebAssembly', 'Emerging Technology', 'Binary Code Format for Web', 'Web', 'WASM', 'ACTIVE'),
('AR/VR', 'Emerging Technology', 'Extended Reality', 'XR', 'AR/VR', 'ACTIVE'),
('Unity', 'Emerging Technology', 'Game Engine & Real-Time 3D', 'Gaming', 'Unity', 'ACTIVE'),
('Unreal Engine', 'Emerging Technology', 'Game Engine', 'Gaming', 'Unreal Engine', 'ACTIVE');

-- 3. Comprehensive Technology Aliases
INSERT INTO skill_aliases (alias_name, skill_id) VALUES
('JS', (SELECT id FROM skills WHERE name = 'JavaScript')),
('ECMAScript', (SELECT id FROM skills WHERE name = 'JavaScript')),
('TS', (SELECT id FROM skills WHERE name = 'TypeScript')),
('Postgres', (SELECT id FROM skills WHERE name = 'PostgreSQL')),
('PostgreSQL DB', (SELECT id FROM skills WHERE name = 'PostgreSQL')),
('PG', (SELECT id FROM skills WHERE name = 'PostgreSQL')),
('K8s', (SELECT id FROM skills WHERE name = 'Kubernetes')),
('Kube', (SELECT id FROM skills WHERE name = 'Kubernetes')),
('TF', (SELECT id FROM skills WHERE name = 'Terraform')),
('GCP', (SELECT id FROM skills WHERE name = 'Google Cloud Platform')),
('Google Cloud', (SELECT id FROM skills WHERE name = 'Google Cloud Platform')),
('AWS', (SELECT id FROM skills WHERE name = 'Amazon Web Services')),
('AWS Cloud', (SELECT id FROM skills WHERE name = 'Amazon Web Services')),
('Azure', (SELECT id FROM skills WHERE name = 'Microsoft Azure')),
('MS Azure', (SELECT id FROM skills WHERE name = 'Microsoft Azure')),
('OCI', (SELECT id FROM skills WHERE name = 'Oracle Cloud Infrastructure')),
('MS SQL', (SELECT id FROM skills WHERE name = 'Microsoft SQL Server')),
('MSSQL', (SELECT id FROM skills WHERE name = 'Microsoft SQL Server')),
('SQL Server', (SELECT id FROM skills WHERE name = 'Microsoft SQL Server')),
('Mongo', (SELECT id FROM skills WHERE name = 'MongoDB')),
('CSharp', (SELECT id FROM skills WHERE name = 'C#')),
('C-Sharp', (SELECT id FROM skills WHERE name = 'C#')),
('Golang', (SELECT id FROM skills WHERE name = 'Go')),
('Rails', (SELECT id FROM skills WHERE name = 'Ruby on Rails')),
('RoR', (SELECT id FROM skills WHERE name = 'Ruby on Rails')),
('Vue', (SELECT id FROM skills WHERE name = 'Vue.js')),
('VueJS', (SELECT id FROM skills WHERE name = 'Vue.js')),
('Vue3', (SELECT id FROM skills WHERE name = 'Vue.js')),
('ReactJS', (SELECT id FROM skills WHERE name = 'React')),
('React.js', (SELECT id FROM skills WHERE name = 'React')),
('NextJS', (SELECT id FROM skills WHERE name = 'Next.js')),
('Next', (SELECT id FROM skills WHERE name = 'Next.js')),
('Nuxt', (SELECT id FROM skills WHERE name = 'Nuxt.js')),
('NuxtJS', (SELECT id FROM skills WHERE name = 'Nuxt.js')),
('AngularJS', (SELECT id FROM skills WHERE name = 'Angular')),
('Svelte.js', (SELECT id FROM skills WHERE name = 'Svelte')),
('Node', (SELECT id FROM skills WHERE name = 'Node.js')),
('NodeJS', (SELECT id FROM skills WHERE name = 'Node.js')),
('ExpressJS', (SELECT id FROM skills WHERE name = 'Express')),
('Express.js', (SELECT id FROM skills WHERE name = 'Express')),
('DotNet', (SELECT id FROM skills WHERE name = '.NET')),
('.NET Core', (SELECT id FROM skills WHERE name = '.NET')),
('DotNet Core', (SELECT id FROM skills WHERE name = '.NET')),
('Spring', (SELECT id FROM skills WHERE name = 'Spring Framework')),
('SpringBoot', (SELECT id FROM skills WHERE name = 'Spring Boot')),
('JPA', (SELECT id FROM skills WHERE name = 'Hibernate')),
('DL', (SELECT id FROM skills WHERE name = 'Deep Learning')),
('ML', (SELECT id FROM skills WHERE name = 'Machine Learning')),
('NLP', (SELECT id FROM skills WHERE name = 'Natural Language Processing')),
('CV', (SELECT id FROM skills WHERE name = 'Computer Vision')),
('RL', (SELECT id FROM skills WHERE name = 'Reinforcement Learning')),
('GAN', (SELECT id FROM skills WHERE name = 'Generative Adversarial Networks')),
('GANs', (SELECT id FROM skills WHERE name = 'Generative Adversarial Networks')),
('LLM', (SELECT id FROM skills WHERE name = 'Large Language Models')),
('LLMs', (SELECT id FROM skills WHERE name = 'Large Language Models')),
('GenAI', (SELECT id FROM skills WHERE name = 'Large Language Models')),
('Gen AI', (SELECT id FROM skills WHERE name = 'Large Language Models')),
('Generative AI', (SELECT id FROM skills WHERE name = 'Large Language Models')),
('GPT', (SELECT id FROM skills WHERE name = 'Large Language Models')),
('GPT-3', (SELECT id FROM skills WHERE name = 'Large Language Models')),
('GPT-3.5', (SELECT id FROM skills WHERE name = 'Large Language Models')),
('GPT-4o', (SELECT id FROM skills WHERE name = 'GPT-4')),
('Claude 3', (SELECT id FROM skills WHERE name = 'Claude')),
('Claude 3.5 Sonnet', (SELECT id FROM skills WHERE name = 'Claude')),
('Llama', (SELECT id FROM skills WHERE name = 'Llama 3')),
('Llama 2', (SELECT id FROM skills WHERE name = 'Llama 3')),
('Retrieval-Augmented Generation', (SELECT id FROM skills WHERE name = 'RAG')),
('Retrieval Augmented Generation', (SELECT id FROM skills WHERE name = 'RAG')),
('Dense Retrieval', (SELECT id FROM skills WHERE name = 'Semantic Search')),
('Embeddings', (SELECT id FROM skills WHERE name = 'Vector Embeddings')),
('Agent', (SELECT id FROM skills WHERE name = 'AI Agents')),
('Agents', (SELECT id FROM skills WHERE name = 'AI Agents')),
('Autonomous Agent', (SELECT id FROM skills WHERE name = 'AI Agents')),
('MCP Protocol', (SELECT id FROM skills WHERE name = 'Model Context Protocol')),
('MCP', (SELECT id FROM skills WHERE name = 'Model Context Protocol')),
('IaC', (SELECT id FROM skills WHERE name = 'Infrastructure as Code')),
('GHA', (SELECT id FROM skills WHERE name = 'GitHub Actions')),
('GitLab CI', (SELECT id FROM skills WHERE name = 'GitLab CI/CD')),
('Elastic', (SELECT id FROM skills WHERE name = 'Elasticsearch')),
('ELK', (SELECT id FROM skills WHERE name = 'ELK Stack')),
('sklearn', (SELECT id FROM skills WHERE name = 'scikit-learn')),
('sk-learn', (SELECT id FROM skills WHERE name = 'scikit-learn')),
('REST', (SELECT id FROM skills WHERE name = 'REST API Design')),
('RESTful', (SELECT id FROM skills WHERE name = 'REST API Design')),
('REST APIs', (SELECT id FROM skills WHERE name = 'REST API Design')),
('RESTful API', (SELECT id FROM skills WHERE name = 'REST API Design')),
('DSA', (SELECT id FROM skills WHERE name = 'Data Structures & Algorithms')),
('Algorithms', (SELECT id FROM skills WHERE name = 'Data Structures & Algorithms')),
('Data Structures', (SELECT id FROM skills WHERE name = 'Data Structures & Algorithms')),
('OOP', (SELECT id FROM skills WHERE name = 'Object-Oriented Design')),
('OOD', (SELECT id FROM skills WHERE name = 'Object-Oriented Design')),
('Object Oriented Programming', (SELECT id FROM skills WHERE name = 'Object-Oriented Design')),
('Git', (SELECT id FROM skills WHERE name = 'Git & Version Control')),
('GitHub', (SELECT id FROM skills WHERE name = 'Git & Version Control')),
('GitLab', (SELECT id FROM skills WHERE name = 'Git & Version Control')),
('Version Control', (SELECT id FROM skills WHERE name = 'Git & Version Control')),
('CI CD', (SELECT id FROM skills WHERE name = 'CI/CD')),
('CICD', (SELECT id FROM skills WHERE name = 'CI/CD')),
('PenTest', (SELECT id FROM skills WHERE name = 'Penetration Testing')),
('Pen Testing', (SELECT id FROM skills WHERE name = 'Penetration Testing')),
('AppSec', (SELECT id FROM skills WHERE name = 'Application Security')),
('CloudSec', (SELECT id FROM skills WHERE name = 'Cloud Security')),
('SecOps', (SELECT id FROM skills WHERE name = 'Application Security')),
('DevSecOps', (SELECT id FROM skills WHERE name = 'Application Security')),
('Tailwind', (SELECT id FROM skills WHERE name = 'Tailwind CSS')),
('TailwindCSS', (SELECT id FROM skills WHERE name = 'Tailwind CSS')),
('MUI', (SELECT id FROM skills WHERE name = 'Material UI')),
('Shadcn', (SELECT id FROM skills WHERE name = 'Shadcn UI')),
('Chakra', (SELECT id FROM skills WHERE name = 'Chakra UI')),
('AntD', (SELECT id FROM skills WHERE name = 'Ant Design')),
('React Native Expo', (SELECT id FROM skills WHERE name = 'Expo')),
('WASM', (SELECT id FROM skills WHERE name = 'WebAssembly')),
('Sol', (SELECT id FROM skills WHERE name = 'Solidity')),
('ETH', (SELECT id FROM skills WHERE name = 'Ethereum')),
('BTC', (SELECT id FROM skills WHERE name = 'Bitcoin')),
('Web3', (SELECT id FROM skills WHERE name = 'Blockchain')),
('BigQuery', (SELECT id FROM skills WHERE name = 'Google BigQuery')),
('Redshift', (SELECT id FROM skills WHERE name = 'Amazon Redshift')),
('DynamoDB', (SELECT id FROM skills WHERE name = 'Amazon DynamoDB')),
('Cosmos DB', (SELECT id FROM skills WHERE name = 'Azure Cosmos DB')),
('CosmosDB', (SELECT id FROM skills WHERE name = 'Azure Cosmos DB')),
('S3', (SELECT id FROM skills WHERE name = 'Amazon S3')),
('GCS', (SELECT id FROM skills WHERE name = 'Google Cloud Storage')),
('E2E', (SELECT id FROM skills WHERE name = 'End-to-End Testing')),
('TDD', (SELECT id FROM skills WHERE name = 'Test-Driven Development')),
('BDD', (SELECT id FROM skills WHERE name = 'Test-Driven Development')),
('Microservices', (SELECT id FROM skills WHERE name = 'Microservices Architecture')),
('Monolith', (SELECT id FROM skills WHERE name = 'Monolithic Architecture')),
('EDA', (SELECT id FROM skills WHERE name = 'Event-Driven Architecture')),
('DDD', (SELECT id FROM skills WHERE name = 'Domain-Driven Design')),
('JWT', (SELECT id FROM skills WHERE name = 'JSON Web Tokens')),
('OIDC', (SELECT id FROM skills WHERE name = 'OpenID Connect')),
('OAuth', (SELECT id FROM skills WHERE name = 'OAuth 2.0')),
('OAuth2', (SELECT id FROM skills WHERE name = 'OAuth 2.0')),
('ZK Proofs', (SELECT id FROM skills WHERE name = 'Zero-Knowledge Proofs')),
('ZKP', (SELECT id FROM skills WHERE name = 'Zero-Knowledge Proofs')),
('Protobuf', (SELECT id FROM skills WHERE name = 'Protocol Buffers')),
('WebSocket', (SELECT id FROM skills WHERE name = 'WebSockets')),
('SSE', (SELECT id FROM skills WHERE name = 'Server-Sent Events'));

-- 4. Key Directed Technology Relationships & Hierarchies
INSERT INTO skill_relationships (source_skill_id, target_skill_id, relationship_type, strength) VALUES
((SELECT id FROM skills WHERE name = 'Java'), (SELECT id FROM skills WHERE name = 'Spring Boot'), 'PARENT', 0.8),
((SELECT id FROM skills WHERE name = 'Java'), (SELECT id FROM skills WHERE name = 'Spring Framework'), 'PARENT', 0.8),
((SELECT id FROM skills WHERE name = 'Java'), (SELECT id FROM skills WHERE name = 'Hibernate'), 'PARENT', 0.7),
((SELECT id FROM skills WHERE name = 'Java'), (SELECT id FROM skills WHERE name = 'Quarkus'), 'PARENT', 0.8),
((SELECT id FROM skills WHERE name = 'Java'), (SELECT id FROM skills WHERE name = 'Micronaut'), 'PARENT', 0.75),
((SELECT id FROM skills WHERE name = 'Spring Boot'), (SELECT id FROM skills WHERE name = 'Spring Framework'), 'RELATED', 0.9),
((SELECT id FROM skills WHERE name = 'Spring Boot'), (SELECT id FROM skills WHERE name = 'Spring Cloud'), 'PARENT', 0.85),
((SELECT id FROM skills WHERE name = 'Spring Boot'), (SELECT id FROM skills WHERE name = 'Spring Security'), 'RELATED', 0.8),
((SELECT id FROM skills WHERE name = 'Spring Boot'), (SELECT id FROM skills WHERE name = 'Hibernate'), 'RELATED', 0.7),
((SELECT id FROM skills WHERE name = 'Spring Boot'), (SELECT id FROM skills WHERE name = 'REST API Design'), 'RELATED', 0.7),
((SELECT id FROM skills WHERE name = 'Java'), (SELECT id FROM skills WHERE name = 'Kotlin'), 'RELATED', 0.7),
((SELECT id FROM skills WHERE name = 'Java'), (SELECT id FROM skills WHERE name = 'Scala'), 'RELATED', 0.6),
((SELECT id FROM skills WHERE name = 'Java'), (SELECT id FROM skills WHERE name = 'JUnit 5'), 'RELATED', 0.6),
((SELECT id FROM skills WHERE name = 'JavaScript'), (SELECT id FROM skills WHERE name = 'TypeScript'), 'RELATED', 0.9),
((SELECT id FROM skills WHERE name = 'JavaScript'), (SELECT id FROM skills WHERE name = 'React'), 'PARENT', 0.8),
((SELECT id FROM skills WHERE name = 'JavaScript'), (SELECT id FROM skills WHERE name = 'Angular'), 'PARENT', 0.7),
((SELECT id FROM skills WHERE name = 'JavaScript'), (SELECT id FROM skills WHERE name = 'Vue.js'), 'PARENT', 0.7),
((SELECT id FROM skills WHERE name = 'JavaScript'), (SELECT id FROM skills WHERE name = 'Svelte'), 'PARENT', 0.7),
((SELECT id FROM skills WHERE name = 'JavaScript'), (SELECT id FROM skills WHERE name = 'Node.js'), 'PARENT', 0.8),
((SELECT id FROM skills WHERE name = 'React'), (SELECT id FROM skills WHERE name = 'Next.js'), 'PARENT', 0.85),
((SELECT id FROM skills WHERE name = 'React'), (SELECT id FROM skills WHERE name = 'Remix'), 'PARENT', 0.8),
((SELECT id FROM skills WHERE name = 'React'), (SELECT id FROM skills WHERE name = 'React Native'), 'RELATED', 0.75),
((SELECT id FROM skills WHERE name = 'React'), (SELECT id FROM skills WHERE name = 'Redux'), 'RELATED', 0.7),
((SELECT id FROM skills WHERE name = 'React'), (SELECT id FROM skills WHERE name = 'Zustand'), 'RELATED', 0.7),
((SELECT id FROM skills WHERE name = 'React'), (SELECT id FROM skills WHERE name = 'TanStack Query'), 'RELATED', 0.7),
((SELECT id FROM skills WHERE name = 'Node.js'), (SELECT id FROM skills WHERE name = 'Express'), 'PARENT', 0.8),
((SELECT id FROM skills WHERE name = 'Node.js'), (SELECT id FROM skills WHERE name = 'NestJS'), 'PARENT', 0.75),
((SELECT id FROM skills WHERE name = 'Node.js'), (SELECT id FROM skills WHERE name = 'Fastify'), 'PARENT', 0.75),
((SELECT id FROM skills WHERE name = 'Vue.js'), (SELECT id FROM skills WHERE name = 'Nuxt.js'), 'PARENT', 0.85),
((SELECT id FROM skills WHERE name = 'Svelte'), (SELECT id FROM skills WHERE name = 'SvelteKit'), 'PARENT', 0.85),
((SELECT id FROM skills WHERE name = 'Python'), (SELECT id FROM skills WHERE name = 'Django'), 'PARENT', 0.8),
((SELECT id FROM skills WHERE name = 'Python'), (SELECT id FROM skills WHERE name = 'Flask'), 'PARENT', 0.7),
((SELECT id FROM skills WHERE name = 'Python'), (SELECT id FROM skills WHERE name = 'FastAPI'), 'PARENT', 0.8),
((SELECT id FROM skills WHERE name = 'Python'), (SELECT id FROM skills WHERE name = 'PyTorch'), 'PARENT', 0.7),
((SELECT id FROM skills WHERE name = 'Python'), (SELECT id FROM skills WHERE name = 'TensorFlow'), 'PARENT', 0.7),
((SELECT id FROM skills WHERE name = 'Python'), (SELECT id FROM skills WHERE name = 'scikit-learn'), 'PARENT', 0.7),
((SELECT id FROM skills WHERE name = 'Python'), (SELECT id FROM skills WHERE name = 'Pandas'), 'PARENT', 0.7),
((SELECT id FROM skills WHERE name = 'Python'), (SELECT id FROM skills WHERE name = 'NumPy'), 'PARENT', 0.7),
((SELECT id FROM skills WHERE name = 'Python'), (SELECT id FROM skills WHERE name = 'LangChain'), 'PARENT', 0.65),
((SELECT id FROM skills WHERE name = 'Python'), (SELECT id FROM skills WHERE name = 'LlamaIndex'), 'PARENT', 0.65),
((SELECT id FROM skills WHERE name = 'C#'), (SELECT id FROM skills WHERE name = '.NET'), 'PARENT', 0.9),
((SELECT id FROM skills WHERE name = '.NET'), (SELECT id FROM skills WHERE name = 'ASP.NET Core'), 'PARENT', 0.85),
((SELECT id FROM skills WHERE name = 'Ruby'), (SELECT id FROM skills WHERE name = 'Ruby on Rails'), 'PARENT', 0.9),
((SELECT id FROM skills WHERE name = 'PHP'), (SELECT id FROM skills WHERE name = 'Laravel'), 'PARENT', 0.85),
((SELECT id FROM skills WHERE name = 'Go'), (SELECT id FROM skills WHERE name = 'Gin'), 'PARENT', 0.8),
((SELECT id FROM skills WHERE name = 'Go'), (SELECT id FROM skills WHERE name = 'Docker'), 'RELATED', 0.6),
((SELECT id FROM skills WHERE name = 'Go'), (SELECT id FROM skills WHERE name = 'Kubernetes'), 'RELATED', 0.6),
((SELECT id FROM skills WHERE name = 'Rust'), (SELECT id FROM skills WHERE name = 'Actix Web'), 'PARENT', 0.8),
((SELECT id FROM skills WHERE name = 'Rust'), (SELECT id FROM skills WHERE name = 'Axum'), 'PARENT', 0.8),
((SELECT id FROM skills WHERE name = 'Dart'), (SELECT id FROM skills WHERE name = 'Flutter'), 'PARENT', 0.9),
((SELECT id FROM skills WHERE name = 'Swift'), (SELECT id FROM skills WHERE name = 'SwiftUI'), 'PARENT', 0.9),
((SELECT id FROM skills WHERE name = 'Kotlin'), (SELECT id FROM skills WHERE name = 'Jetpack Compose'), 'PARENT', 0.85),
((SELECT id FROM skills WHERE name = 'Machine Learning'), (SELECT id FROM skills WHERE name = 'Deep Learning'), 'PARENT', 0.8),
((SELECT id FROM skills WHERE name = 'Deep Learning'), (SELECT id FROM skills WHERE name = 'Natural Language Processing'), 'RELATED', 0.7),
((SELECT id FROM skills WHERE name = 'Deep Learning'), (SELECT id FROM skills WHERE name = 'Computer Vision'), 'RELATED', 0.7),
((SELECT id FROM skills WHERE name = 'Deep Learning'), (SELECT id FROM skills WHERE name = 'PyTorch'), 'RELATED', 0.8),
((SELECT id FROM skills WHERE name = 'Deep Learning'), (SELECT id FROM skills WHERE name = 'TensorFlow'), 'RELATED', 0.8),
((SELECT id FROM skills WHERE name = 'Large Language Models'), (SELECT id FROM skills WHERE name = 'RAG'), 'RELATED', 0.85),
((SELECT id FROM skills WHERE name = 'Large Language Models'), (SELECT id FROM skills WHERE name = 'Prompt Engineering'), 'RELATED', 0.8),
((SELECT id FROM skills WHERE name = 'Large Language Models'), (SELECT id FROM skills WHERE name = 'Fine-tuning'), 'RELATED', 0.75),
((SELECT id FROM skills WHERE name = 'Large Language Models'), (SELECT id FROM skills WHERE name = 'Vector Embeddings'), 'RELATED', 0.8),
((SELECT id FROM skills WHERE name = 'RAG'), (SELECT id FROM skills WHERE name = 'Vector Embeddings'), 'PREREQUISITE', 0.85),
((SELECT id FROM skills WHERE name = 'RAG'), (SELECT id FROM skills WHERE name = 'Pinecone'), 'RELATED', 0.7),
((SELECT id FROM skills WHERE name = 'RAG'), (SELECT id FROM skills WHERE name = 'Weaviate'), 'RELATED', 0.7),
((SELECT id FROM skills WHERE name = 'RAG'), (SELECT id FROM skills WHERE name = 'ChromaDB'), 'RELATED', 0.7),
((SELECT id FROM skills WHERE name = 'RAG'), (SELECT id FROM skills WHERE name = 'Pgvector'), 'RELATED', 0.7),
((SELECT id FROM skills WHERE name = 'Large Language Models'), (SELECT id FROM skills WHERE name = 'AI Agents'), 'RELATED', 0.8),
((SELECT id FROM skills WHERE name = 'AI Agents'), (SELECT id FROM skills WHERE name = 'Tool Calling'), 'PARENT', 0.85),
((SELECT id FROM skills WHERE name = 'AI Agents'), (SELECT id FROM skills WHERE name = 'Function Calling'), 'PARENT', 0.85),
((SELECT id FROM skills WHERE name = 'AI Agents'), (SELECT id FROM skills WHERE name = 'Agent Memory'), 'RELATED', 0.75),
((SELECT id FROM skills WHERE name = 'AI Agents'), (SELECT id FROM skills WHERE name = 'Agent Orchestration'), 'RELATED', 0.75),
((SELECT id FROM skills WHERE name = 'AI Agents'), (SELECT id FROM skills WHERE name = 'Multi-Agent Systems'), 'RELATED', 0.7),
((SELECT id FROM skills WHERE name = 'AI Agents'), (SELECT id FROM skills WHERE name = 'CrewAI'), 'RELATED', 0.8),
((SELECT id FROM skills WHERE name = 'AI Agents'), (SELECT id FROM skills WHERE name = 'AutoGen'), 'RELATED', 0.8),
((SELECT id FROM skills WHERE name = 'AI Agents'), (SELECT id FROM skills WHERE name = 'Model Context Protocol'), 'RELATED', 0.75),
((SELECT id FROM skills WHERE name = 'Docker'), (SELECT id FROM skills WHERE name = 'Kubernetes'), 'PREREQUISITE', 0.8),
((SELECT id FROM skills WHERE name = 'Docker'), (SELECT id FROM skills WHERE name = 'CI/CD'), 'RELATED', 0.65),
((SELECT id FROM skills WHERE name = 'Kubernetes'), (SELECT id FROM skills WHERE name = 'Helm'), 'RELATED', 0.75),
((SELECT id FROM skills WHERE name = 'Kubernetes'), (SELECT id FROM skills WHERE name = 'ArgoCD'), 'RELATED', 0.7),
((SELECT id FROM skills WHERE name = 'Kubernetes'), (SELECT id FROM skills WHERE name = 'Istio'), 'RELATED', 0.65),
((SELECT id FROM skills WHERE name = 'Terraform'), (SELECT id FROM skills WHERE name = 'Infrastructure as Code'), 'RELATED', 0.9),
((SELECT id FROM skills WHERE name = 'Prometheus'), (SELECT id FROM skills WHERE name = 'Grafana'), 'RELATED', 0.85),
((SELECT id FROM skills WHERE name = 'Data Science'), (SELECT id FROM skills WHERE name = 'Machine Learning'), 'RELATED', 0.85),
((SELECT id FROM skills WHERE name = 'Data Science'), (SELECT id FROM skills WHERE name = 'Pandas'), 'RELATED', 0.75),
((SELECT id FROM skills WHERE name = 'Data Science'), (SELECT id FROM skills WHERE name = 'NumPy'), 'RELATED', 0.75),
((SELECT id FROM skills WHERE name = 'PostgreSQL'), (SELECT id FROM skills WHERE name = 'Pgvector'), 'PARENT', 0.9),
((SELECT id FROM skills WHERE name = 'PostgreSQL'), (SELECT id FROM skills WHERE name = 'TimescaleDB'), 'PARENT', 0.85),
((SELECT id FROM skills WHERE name = 'Application Security'), (SELECT id FROM skills WHERE name = 'OWASP Top 10'), 'RELATED', 0.85),
((SELECT id FROM skills WHERE name = 'Application Security'), (SELECT id FROM skills WHERE name = 'SAST'), 'RELATED', 0.75);
